version: '3.7'
services:
  frontend_server:
   build:
     context: ./client
     dockerfile: Dockerfile.dev
   depends_on:
     - backend_server
   stdin_open: true
   #volumes:
   #- ./client/volume:/app
   ports:
   - 3000:3000

  backend_server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    #volumes:
    #- ./server/volume:/server
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tim123
      POSTGRES_USER: postgres
      POSTGRES_DB: in_docker_db